Panama Withholding
Vauxoo/odoo-panama pull request #42
Opened 2016-10-25 09:01 UTC by hbto

2016-10-25 12:37 UTC, nhomar commented on l10n_pa_withholding/__openerp__.py
> +            "l10n_pa_reports",
Why depend of reports? I was expecting this as a procedural modules only, in all case the one that should depend of this one is the l10n_pa_report

2016-10-25 12:38 UTC, nhomar commented on l10n_pa_withholding/model/account_invoice.py
> +        if line.invoice_id.type in ('out_invoice', 'in_invoice'):
this methodology is only valid for out_invoice and out_refund not for in_invoice that case has not been discussed yet.

2016-10-25 12:39 UTC, nhomar commented on l10n_pa_withholding/model/account_invoice.py
> +        """Creates Withholding for taxes in invoice"""
THe agreement was create an extra account move, not an extra tax.line, why are you coding an extra tax.line?

2016-10-25 12:41 UTC, nhomar commented
I can't see:

- Flag in partner to manage the withholding process.
- Process is not what we discussed, we discussed an extra account move not an extra tag.

Please fix.

2016-10-25 16:44 UTC, hbto commented on l10n_pa_withholding/__openerp__.py
> +            "l10n_pa_reports",
Preliminar proposal not set in stone

2016-10-25 16:45 UTC, hbto commented on l10n_pa_withholding/model/account_invoice.py
> +        if line.invoice_id.type in ('out_invoice', 'in_invoice'):
then just need to override the offending code

2016-10-25 16:46 UTC, hbto commented on l10n_pa_withholding/model/account_invoice.py
> +        """Creates Withholding for taxes in invoice"""
As I have mentioned before to you privately, _there are two commits_ both are to be reviewed widen your sight

2016-10-25 20:47 UTC, hbto commented
- [ ] Field on Partner, Withholding Subject: To Discuss @nhomar, for reporting purpose it needs to be an integer, for business process needs to be a value, do we use a new record for this or do we wire the value to the integer value in Business Process.

2016-10-25 22:11 UTC, nhomar commented
On Tue, Oct 25, 2016 at 3:47 PM, Hbto [ Vauxoo ] <notifications@github.com>
wrote:

>
>    - Field on Partner, Withholding Subject: To Discuss @nhomar
>    <https://github.com/nhomar>, for reporting purpose it needs to be an
>    integer, for business process needs to be a value, do we use a new record
>    for this or do we wire the value to the integer value in Business Process.
>
>
It should be a selection with possible Values:

No Withhold
Percentage 1
Percentage 2
..
...
....
Percentage N


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

2016-10-26 21:33 UTC, hbto commented
@nhomar 
Do we need to propagate info from SaleOrder to Invoice through path
SaleOrder > Picking > Invoice?

2016-10-26 23:36 UTC, hbto commented
@nhomar 

> 
> Do we need to propagate info from SaleOrder to Invoice through path
> SaleOrder > Picking > Invoice?

Already done here:

Propagate Withholding Subject from Sale Order to Invoice, when invoicing from Picking - d3cc67b

2016-10-26 23:44 UTC, nhomar commented on l10n_pa_withholding/__openerp__.py
> +            "stock",
can you add sale_stock to dependencies pliz

2016-10-27 00:58 UTC, hbto commented on l10n_pa_withholding/__openerp__.py
> +            "stock",
@nhomar 
ok, got it

2016-10-27 01:02 UTC, hbto commented on l10n_pa_withholding/__openerp__.py
> +            "stock",
@nhomar Done at 9934518

2016-10-27 02:42 UTC, hbto commented on l10n_pa_withholding/__openerp__.py
> +            "l10n_pa_reports",
@nhomar 
Already fixed @ c866be3

2016-10-27 03:00 UTC, nhomar commented
Según el plan:

- Campo en Aml de objeto de retención para efectos de reportes posteriores?

Puede ser un diario no? o un tipo de diario?

2016-10-28 05:45 UTC, hbto commented
@nhomar 

Following Items are pending:


- [ ] Module Translation into Spanish (DOING)

- [ ] Field in account.move.line for afterwards Withholding Report purposes  - Campo en Aml de objeto de retención para efectos de reportes posteriores?
Can we meet to further discuss this statement of yours
> Puede ser un diario no? o un tipo de diario?
I have some doubts

- [ ] Will we use the same journal than that of the invoice + a String for Journal Entry Naming or a new Journal?
Do you have any idea or can we cross this item, getting rid of it.

- [ ] How to proceed on cancellation of invoice?
What would you suggest?

2016-10-29 05:21 UTC, hbto commented
@nhomar Could you review and provide further guidance.

Regards

2016-10-31 22:55 UTC, nhomar requested changes

2016-10-31 22:55 UTC, nhomar commented on l10n_pa_withholding/model/account_invoice.py
> +    _inherit = 'account.invoice.tax'
don't forget _rec_name

2016-11-01 03:24 UTC, hbto commented on l10n_pa_withholding/model/account_invoice.py
> +    _inherit = 'account.invoice.tax'
There's no need for `_rec_name` I am prototyping from `account.invoice.tax` which already has `name`.

Or should I?
<img width="868" alt="models" src="https://cloud.githubusercontent.com/assets/7598010/19878599/1af6790e-9fc1-11e6-8ff6-6ca0a77836df.png">

2016-11-02 17:07 UTC, hbto commented
@nhomar 
https://drive.google.com/file/d/0B1w9gokcJL9hWHlNRDMzajFyN2M/view

2016-11-03 18:26 UTC, hbto commented
Method to compute taxes needs to be fixed,
When wh_subject is `5` or `6` the withholding is performed based on
the whole invoice amount_total, rather than tax based.

2016-11-08 21:43 UTC, merged